#!/bin/sh

die () { echo $@ ; exit 1; }

. ../../../nvm.sh

set -ex

! nvm_version_dir >/dev/null 2>&1 || die '"nvm_version_dir" did not exit nonzero'
set +x
OUTPUT="$(nvm_version_dir 2>&1 >/dev/null)" ||:
set -x
[ "${OUTPUT}" = 'unknown version dir' ] || die "'nvm_version_dir' did not error with the right message; got >${OUTPUT}<"

[ "$(nvm_version_dir iojs)" = "${NVM_DIR}/versions/io.js" ] || die '"nvm_version_dir iojs" did not return iojs dir path'
[ "$(nvm_version_dir iojs:rc)" = "${NVM_DIR}/versions/release_candidates/io.js" ] || die '"nvm_version_dir iojs:rc" did not return iojs rc dir path'
[ "$(nvm_version_dir new)" = "${NVM_DIR}/versions/node" ] || die '"nvm_version_dir new" did not return new dir path'
[ "$(nvm_version_dir old)" = "${NVM_DIR}" ] || die '"nvm_version_dir old" did not return old dir path'

! nvm_version_dir foo >/dev/null 2>&1 || die '"nvm_version_dir foo" did not exit nonzero'
set +x
OUTPUT="$(nvm_version_dir foo 2>&1 >/dev/null)" ||:
set -x
[ "${OUTPUT}" = 'unknown version dir' ] || die "'nvm_version_dir foo' did not error with the right message; got >${OUTPUT}<"
