#!/bin/sh

die () { echo $@ ; exit 1; }

. ../../../nvm.sh

[ "_$(nvm_add_iojs_rc_prefix 1)" = "_iojs:rc-v1" ] || die '"nvm_add_iojs_rc_prefix 1" did not return "iojs:rc-v1"'
[ "_$(nvm_add_iojs_rc_prefix iojs:rc-1)" = "_iojs:rc-v1" ] || die '"nvm_add_iojs_rc_prefix iojs:rc-1" did not return "iojs:rc-v1"'
[ "_$(nvm_add_iojs_rc_prefix iojs:rc-1.2.3)" = "_iojs:rc-v1.2.3" ] || die '"nvm_add_iojs_rc_prefix iojs:rc-1.2.3" did not return "iojs:rc-v1.2.3"'
