name: urchin tests

on: [pull_request, push]

jobs:
  tests:
    permissions:
      contents: write

    name: "tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'script -q -e -c "${{ matrix.shell }} {0}"'

    # defaults:
    #   run:
    #     # GitHub Actions run without a TTY device. This is a workaround to get one,
    #     # based on https://github.com/actions/runner/issues/241#issuecomment-842566950.
    #     shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'

    strategy:
      fail-fast: false
      matrix:
        shell:
          - bash
          - sh
          - dash
        suite:
          - fast
          # - sourcing
          # - slow
          # - installation_node
          # - installation_iojs
        installer:
          - curl
          - wget
        include:
          - suite: install_script
            shell: bash
            installer: curl
          - suite: install_script
            shell: bash
            installer: wget

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          allowed-endpoints:
            github.com:443
            registry.npmjs.org:443
            raw.githubusercontent.com:443
            nodejs.org:443
            iojs.org:443
      - uses: actions/checkout@v4
      - run: sudo ${{ matrix.shell }} --version 2> /dev/null || dpkg -s ${{ matrix.shell }} 2> /dev/null || which ${{ matrix.shell }}
      - run: curl --version
      - run: wget --version
      - uses: ljharb/actions/node/install@main
        name: 'nvm install node && npm install'
        with:
          node-version: 'lts/*'
          skip-ls-check: true
      - run: npm ls urchin
      - run: npx which urchin
      - run: env
      - run: make TERM=xterm-256color TEST_SUITE="${{ matrix.suite }}" SHELL="${{ matrix.shell }}" URCHIN="$(npx which urchin)" test-${{ matrix.shell }}
        working-directory: ${{ env.NVM_DIR }}
        env:
          SHELL: ${{ matrix.shell }}
          TEST_SUITE: ${{ matrix.suite }}

  nvm:
    name: 'all test suites, all shells'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: true
