name: 'Test Suites'

on: [pull_request, push]

jobs:
  tests:
    name: 'test suites'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "${{ matrix.shell }} {0}"

    strategy:
      matrix:
        shell:
          - bash
          - sh
          - dash
          # - ksh
          # - zsh # https://github.com/actions/virtual-environments/issues/264
        suite:
          - fast
          - sourcing
          - slow
          - installation_node
          - installation_iojs
        installer:
          - curl
          - wget
        include:
          - suite: install_script
            shell: bash
            installer: curl
          - suite: install_script
            shell: bash
            installer: wget

    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.shell }} --version 2> /dev/null || dpkg -s ${{ matrix.shell }} 2> /dev/null || which ${{ matrix.shell }}
      - run: curl --version
      - run: wget --version
      - uses: ljharb/actions/node/run@main
        name: 'npm install && version checks'
        with:
          node-version: 'lts/*'
          skip-ls-check: true
          shell-command: echo installed
      - run: make test-${{ matrix.shell }}
        env:
          TEST_SUITE: ${{ matrix.suite }}
          URCHIN: "$(npm bin)/urchin"

  nvm:
    name: 'all test suites, all shells'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
